### ISSUE TITLE
Don't call ClearState before and after rendering

### ISSUE THREAD

**Issue by LeadRDRK** [Nekomaru-PKU/egui-directx11#1]
Why does the renderer need to clear the state on its own? That seems unnecessary. It already sets the state up for its own rendering, so why need to mess with the entire context, if the other states won't affect rendering? This makes it much more cumbersome for the user, because now, instead of just backing up the states modified by the renderer, I have to backup and restore the entire context's state. Plus, doing many state changes per frame is an expensive operation. It should be the user's responsibility to clear the state or not.

**Comment by Nekomaru-PKU** [comment]
Sorry for my late reply. Sure, calling ClearState is absolutely not a necessity and is just a lazy solution of for my early use. I plan to release a new version and fix this, in, maybe this weekend? Anyway, thanks for your advice and also for trying out my first Rust crate!

**Comment by Nekomaru-PKU** [comment]
@LeadRDRK I have released v0.3.1 and calls to ClearState have been removed. Please check if this issue has been resolved. Also, feel free to contact me or open another issue if you find something else wrong!
