### ISSUE TITLE
Image rendering with lighter colors

### ISSUE THREAD

**Issue by LeadRDRK** [Nekomaru-PKU/egui-directx11#2]
It seems to be using the wrong color space.

- Reference rendering (egui_glow)
![image](https://github.com/Nekomaru-PKU/egui-directx11/assets/25358041/1abe255a-c4c1-4a40-a180-bdfe002e79b2)

- egui-directx11
![image](https://github.com/Nekomaru-PKU/egui-directx11/assets/25358041/de4c4645-2bd1-45fa-8f5e-8b1d29b8210f)

Other widgets are using the correct colors. The render target is using the `DXGI_FORMAT_R8G8B8A8_UNORM_SRGB` format.

**Comment by Nekomaru-PKU** [comment]
Sorry for my late reply. It is certainly a serious issue within this crate that images are not rendered in the correct color space, and is not yet covered in previous tests. I will investigate this and release a fix in, maybe this weekend? Anyway, thanks for your report and also for trying out my first Rust crate!

**Comment by LeadRDRK** [comment]
The issue has been resolved, thank you!
