### ISSUE TITLE
example request

### ISSUE THREAD

**Issue by CheetoTrump** [Nekomaru-PKU/egui-directx11#4]
Can you make an example of how to render shapes i.e squares or circles using dx11 with your crate?

**Comment by Nekomaru-PKU** [comment]
Hmm, I don't think I will add such examples into this repo, and here's the reason: technically, this crate is _not_ something that one can draw shapes, UI elements or any other things with. This crate is neither a graphics library nor a UI library, and will never be one. Instead, this crate `egui-directx11`, as its name suggests, is a glue between a (relatively) low-level graphics API set, namely Direct3D 11 (informally called DirectX 11), and a high-level UI rendering library, namely `egui`. If you are not familiar with either of them, this crate is definitely not what you are looking for.

If you just want a crate that takes care of things about rendering 2D shapes or UI elements, you may start from the 2D Rendering or 3D Rendering part on [Are we game yet?](https://arewegameyet.rs/#ecosystem). If you are creating a game or a graphics application, that may help as well.

If you are using `egui` and you would like to do some custom drawing, you may check the documentation as well as examples of `egui` and [`epaint`](https://docs.rs/epaint/0.28.1). The latter is a part of the `egui` project and handles 2D rendering for `egui`. You may also check the [egui online demo](https://www.egui.rs/#Demo) and its source code at [`egui_demo_lib`](https://github.com/emilk/egui/tree/master/crates/egui_demo_lib/src/demo). Some of the examples in the demo, for example [paint_bezier.rs](https://github.com/emilk/egui/blob/master/crates/egui_demo_lib/src/demo/paint_bezier.rs), demonstrate how to do custom 2D drawing using `egui` and `epaint`.

If you would like to do rendering stuff directly on the graphics pipeline, you may have to be quite familiar with one of the graphics APIs: OpenGL, Direct3D, Metal or WebGPU. It is not a easy thing to explain how to draw a triangle using one of them without tens of pages talking about programmable pipeline stuff.

**Comment by CheetoTrump** [comment]
alright, i was hoping to be able to draw outside of the egui menu on the winit tab for a small game im making that is just 2d

**Comment by Nekomaru-PKU** [comment]
Seems a good time for some new examples! Let's go!!
